### PR TITLE
Update MathJax to v3

### LINKED ISSUE #297: MathJax v3
This isn't a bug report, I just want to bring something to your attention in case it ends up mattering later.

MathJax v3 was pretty much a total rewrite. It speeds things up considerably, which is great. The way it is configured has changed, so it isn't as simple as changing 2.7.4 to 3.0.0 in your mathjax partial. I'll let you know if I get around to trying it out, and I'll let you know if any math that I use breaks from it. It'll be a little while because I'm trying to finish writing a thesis.

Here's a page with some of the details: https://docs.mathjax.org/en/latest/upgrading/v2.html

### PR DESCRIPTION
**Pull request by benide**
I used [this tool](https://mathjax.github.io/MathJax-demos-web/convert-configuration/convert-configuration.html) to convert the config. Assuming this doesn't break any tests, this can close kaushalmodi/ox-hugo#297.

### CODE REVIEW

**Comment by benide** [comment]
It does seem to work with everything I had used it with before, but I'm finding there are some things I can improve on. Don't merge just yet!

**Comment by benide** [comment]
OK, the only things I can find wrong with this are already fixed over at the mathjax repo, but not in an official release yet. mathjax/MathJax#2186 is a little annoying but certainly not breaking. mathjax/MathJax-src#335 could be breaking for people using amsCd, but will be fixed in 3.0.1. Other than the first (non-breaking) bug I linked, I think nothing should change on your test site. Importantly, `\ref{...}` still works.

**Comment by kaushalmodi** [comment]
Thanks! Merging this.

**Comment by kaushalmodi** [comment]
Manually merged in https://github.com/kaushalmodi/hugo-bare-min-theme/commit/4958d996e3cc2c59d73b2c7d665105a64c7b24a5.

**Pull request closed without merging**
